/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.apache.kafka.common.metrics;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
