/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.apache.kafka.common.metrics;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class PrometheusReporterTest {
    @Test
    void testSomeLibraryMethod() {
        assertTrue(true);
    }
}
